version: 2

project_name: devcontract

before:
  hooks:
    - go mod tidy

builds:
  - id: devcontract
    main: .
    binary: devcontract
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/dantwoashim/devcontract/cmd.Version={{.Version}}
      - -X github.com/dantwoashim/devcontract/cmd.GitCommit={{.ShortCommit}}
      - -X github.com/dantwoashim/devcontract/cmd.BuildDate={{.Date}}

archives:
  - id: default
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"

release:
  github:
    owner: dantwoashim
    name: DevContract
  draft: false
  prerelease: auto
