// Copyright (c) DevContract Contributors. SPDX-License-Identifier: MIT

package cmd

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"

	"github.com/dantwoashim/devcontract/internal/config"
	"github.com/dantwoashim/devcontract/internal/contract"
	"github.com/dantwoashim/devcontract/internal/crypto"
	"github.com/dantwoashim/devcontract/internal/envfile"
	"github.com/dantwoashim/devcontract/internal/fsutil"
)

type contractContext struct {
	Root     string
	Path     string
	Contract *contract.Contract
}

func loadContractContext() (*contractContext, error) {
	spec, path, err := contract.LoadProject()
	if err != nil {
		return nil, err
	}
	return &contractContext{
		Root:     filepath.Dir(filepath.Dir(path)),
		Path:     path,
		Contract: spec,
	}, nil
}

func requireContractContext() (*contractContext, error) {
	ctx, err := loadContractContext()
	if err == nil {
		return ctx, nil
	}
	return nil, fmt.Errorf("%w\n\n  Run 'devcontract init' to create %s", err, config.ContractFilePath())
}

func ensureProjectContract(project *projectContext) (string, bool, error) {
	projectName := filepath.Base(mustGetwd())
	if project != nil && project.Config != nil && project.Config.Name != "" {
		projectName = project.Config.Name
	}

	path := config.ContractFilePath()
	created, err := contract.EnsureDefault(path, projectName)
	return path, created, err
}

func repoEnvValues(root string, spec *contract.Contract, targetFile string) map[string]string {
	values := map[string]string{}
	for _, item := range os.Environ() {
		parts := strings.SplitN(item, "=", 2)
		if len(parts) == 2 {
			values[parts[0]] = parts[1]
		}
	}

	files := []string{}
	if targetFile != "" {
		files = append(files, targetFile)
	}
	if spec != nil {
		for _, output := range spec.Bootstrap.Outputs {
			if output.Kind == "env" || strings.HasPrefix(filepath.Base(output.Path), ".env") {
				files = append(files, filepath.Join(root, output.Path))
			}
		}
	}

	seen := map[string]struct{}{}
	for _, path := range files {
		if path == "" {
			continue
		}
		if _, ok := seen[path]; ok {
			continue
		}
		seen[path] = struct{}{}

		data, err := os.ReadFile(path)
		if err != nil {
			continue
		}
		parsed, err := envfile.Parse(string(data))
		if err != nil {
			continue
		}
		for _, entry := range parsed.Entries {
			if entry.Type == envfile.EntryKeyValue {
				values[entry.Key] = entry.Value
			}
		}
	}

	return values
}

func ensureBootstrapOutput(root string, spec contract.BootstrapOutput, envNames []string) (bool, error) {
	path, err := safeRepoPath(root, spec.Path)
	if err != nil {
		return false, err
	}

	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return false, err
	}

	content := renderBootstrapOutput(spec, envNames)
	created := false
	switch bootstrapOutputRefreshMode(spec) {
	case "manual":
		// Never mutate files managed manually.
	case "refresh-managed":
		current, readErr := os.ReadFile(path)
		if os.IsNotExist(readErr) {
			created = true
			if err := fsutil.AtomicWriteFile(path, []byte(content), bootstrapOutputMode(spec)); err != nil {
				return false, err
			}
		} else if readErr == nil && isManagedBootstrapOutput(string(current)) && string(current) != content {
			if err := fsutil.AtomicWriteFile(path, []byte(content), bootstrapOutputMode(spec)); err != nil {
				return false, err
			}
		} else if readErr != nil {
			return false, readErr
		}
	default:
		if _, err := os.Stat(path); os.IsNotExist(err) {
			created = true
			if err := fsutil.AtomicWriteFile(path, []byte(content), bootstrapOutputMode(spec)); err != nil {
				return false, err
			}
		}
	}

	if spec.Gitignore {
		if err := ensureGitignoreEntry(root, spec.Path); err != nil {
			return created, err
		}
	}

	return created, nil
}

func bootstrapOutputRefreshMode(spec contract.BootstrapOutput) string {
	if spec.Mode == "" {
		return "create-if-missing"
	}
	return spec.Mode
}

func bootstrapOutputMode(spec contract.BootstrapOutput) os.FileMode {
	if spec.Kind == "env" || strings.HasPrefix(filepath.Base(spec.Path), ".env") {
		return 0600
	}
	return 0644
}

func renderBootstrapOutput(spec contract.BootstrapOutput, envNames []string) string {
	if spec.Kind != "env" && !strings.HasPrefix(filepath.Base(spec.Path), ".env") {
		if spec.Header != "" {
			return "# Generated by DevContract bootstrap\n# " + spec.Header + "\n"
		}
		return "# Generated by DevContract bootstrap\n"
	}

	var b strings.Builder
	b.WriteString("# Generated by DevContract bootstrap\n")
	if spec.Header != "" {
		b.WriteString("# " + spec.Header + "\n")
	}
	for _, name := range envNames {
		fmt.Fprintf(&b, "# %s=\n", name)
	}
	return b.String()
}

func isManagedBootstrapOutput(content string) bool {
	return strings.HasPrefix(content, "# Generated by DevContract bootstrap\n")
}

func ensureGitignoreEntry(root, relativePath string) error {
	gitignorePath := filepath.Join(root, ".gitignore")
	entry := filepath.ToSlash(relativePath)

	data, err := os.ReadFile(gitignorePath)
	if err == nil {
		for _, line := range strings.Split(string(data), "\n") {
			if strings.TrimSpace(line) == entry {
				return nil
			}
		}
	}

	f, err := os.OpenFile(gitignorePath, os.O_CREATE|os.O_APPEND|os.O_WRONLY, 0644)
	if err != nil {
		return err
	}
	defer f.Close()

	if _, err := fmt.Fprintf(f, "\n%s\n", entry); err != nil {
		return err
	}
	return nil
}

func safeRepoPath(root, relativePath string) (string, error) {
	if filepath.IsAbs(relativePath) {
		return "", fmt.Errorf("path %s must be relative to the repo root", relativePath)
	}

	cleanRoot, err := filepath.Abs(root)
	if err != nil {
		return "", err
	}
	fullPath := filepath.Join(cleanRoot, filepath.Clean(relativePath))
	if rel, err := filepath.Rel(cleanRoot, fullPath); err != nil || strings.HasPrefix(rel, "..") {
		return "", fmt.Errorf("path %s escapes the repo root", relativePath)
	}
	return fullPath, nil
}

func commandExists(binary string) bool {
	if binary == "" {
		return false
	}
	_, err := exec.LookPath(binary)
	return err == nil
}

func commandVersion(binary string, args []string) string {
	if binary == "" {
		return ""
	}
	cmd := exec.Command(binary, args...)
	output, err := cmd.CombinedOutput()
	if err != nil {
		return strings.TrimSpace(string(output))
	}
	return strings.TrimSpace(string(output))
}

func renderShellCommand(shellName, command string) string {
	if strings.TrimSpace(command) == "" {
		return ""
	}

	switch {
	case shellName == "bash":
		return fmt.Sprintf("bash -lc %q", command)
	case shellName == "sh":
		return fmt.Sprintf("sh -lc %q", command)
	case shellName == "powershell":
		return fmt.Sprintf("powershell -Command %q", command)
	case runtime.GOOS == "windows":
		return fmt.Sprintf("cmd /C %q", command)
	default:
		return fmt.Sprintf("sh -lc %q", command)
	}
}

func contractShellCommands(spec *contract.Contract) []string {
	if spec == nil {
		return nil
	}

	commands := []string{}
	for _, step := range spec.Bootstrap.Steps {
		if strings.TrimSpace(step.Run) == "" {
			continue
		}
		commands = append(commands, renderShellCommand(step.Shell, step.Run))
	}
	for name, target := range spec.Run.Targets {
		if strings.TrimSpace(target.Command) == "" {
			continue
		}
		commands = append(commands, fmt.Sprintf("%s (run target %s)", renderShellCommand("", target.Command), name))
	}
	return commands
}

func runShellCommand(root, shellName, command string) error {
	if strings.TrimSpace(command) == "" {
		return nil
	}

	var cmd *exec.Cmd
	switch {
	case shellName == "bash":
		cmd = exec.Command("bash", "-lc", command)
	case shellName == "sh":
		cmd = exec.Command("sh", "-lc", command)
	case shellName == "powershell":
		cmd = exec.Command("powershell", "-Command", command)
	case runtime.GOOS == "windows":
		cmd = exec.Command("cmd", "/C", command)
	default:
		cmd = exec.Command("sh", "-lc", command)
	}
	cmd.Dir = root
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	return cmd.Run()
}

func loadIdentityIfAvailable() (*crypto.KeyPair, error) {
	cfg, err := loadConfig()
	if err != nil {
		return nil, err
	}
	if cfg.Identity.SSHKeyPath == "" {
		return nil, fmt.Errorf("identity not configured")
	}
	return loadIdentity()
}
